### ISSUE TITLE
Phar in releases

### ISSUE THREAD

**Issue by NicolasCARPi** [NielsdeBlaauw/php-doc-check#2]
Hello,

I want to use this tool but I don't want to pollute my composer.json file. I've taken into habit to use the phar version of static analyzers (phan, phpstan, psalm, phpdoc…) so I'm sure I'll never run into dependencies clash.

Please consider releasing a (signed) phar archive :)

Cheers,
~Nico

**Comment by NielsdeBlaauw** [comment]
Hi @NicolasCARPi 

Thanks for the suggestion. I'll look into how to build a phar version of this package. I must admit I have not done this before, so it might take some effort. If you have any resources or pointers to help me on the way, any help is welcome.

**Comment by NicolasCARPi** [comment]
This is a good read: https://medium.com/@tfidry/create-and-deploy-secure-phars-c5572f10b4dd
