### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by rockoo** [NielsdeBlaauw/php-doc-check#4]
There is some failure half through analysis and it throws the following exception:

`
.PHP Fatal error:  Uncaught PhpParser\Error: Unexpected null byte on line 1 in ...vendor/nikic/php-parser/lib/PhpParser/Lexer.php:100
`

**Comment by NielsdeBlaauw** [comment]
Thanks @rockoo for the bug report. This seems to be the problem I found in #1. It basically means the file you are checking is not a valid php file.

For #1 I will improve how these exceptions are handled. Do you mind if I ask you to try the same run again after I have fixed it, to see if that also fixes this issue?

**Comment by NielsdeBlaauw** [comment]
Hi @rockoo, @petardfoozer 

The fix of #1 is now merged and should also resolve this issue. Could you retry the command that failed before, to see if it no longer crashes on unparsable files?

**Comment by NielsdeBlaauw** [comment]
I am considering this fixed.

**Comment by rockoo** [comment]
@NielsdeBlaauw thank you for fast response and sorry for my late reply. For some reason I didnt get an email nor it showed me notification.

It is fixed! Thank you
