### ISSUE TITLE
Comments for anonymous functions not detected

### ISSUE THREAD

**Issue by menno-ll** [NielsdeBlaauw/php-doc-check#56]
Comments of anonymous functions are not always detected.

![image](https://user-images.githubusercontent.com/50165380/73756558-1011e300-4768-11ea-972e-dff78df9857e.png)
![image](https://user-images.githubusercontent.com/50165380/73756583-1902b480-4768-11ea-8506-5edd5f20c7d9.png)

**Comment by NielsdeBlaauw** [comment]
Anonymous functions can now be ignored with the `-a` arg.
